language: go

go:
  - 1.6
  - 1.7

install:
  - go get github.com/kelseyhightower/envconfig
  - go get github.com/codegangsta/negroni
  - go get github.com/gorilla/mux

build:
  - make get-glide
  - make build

test:
  - go test -v ./...
