development:
  dialect: mysql
  database: episode24_development
  user: ep24
  password: ep24
  host: 127.0.0.1
  pool: 5

test:
  dialect: mysql
  database: episode24_test
  user: ep24
  password: ep24
  host: 127.0.0.1
  pool: 5

production:
  dialect: mysql
  database: episode24_prod
  user: ep24
  password: ep24
  host: 127.0.0.1
  pool: 5
