# This is a task file, for use with go-task. See https://taskfile.dev/#/ for details
#
# GH site for this tool: https://github.com/go-task/task
version: '2'
output: prefixed
tasks:
    default:
        deps:
            - api
            - hugo
            - elm
            - caddy
            - postgres
    api:
        dir: api
        cmds:
            - buffalo dev
    dbmigrate:
        dir: api
        cmds: [buffalo db migrate up]
    postgres:
        cmds:
            - |
                docker run \
                    -e POSTGRES_PASSWORD=postgres \
                    -e POSTGRES_USER=postgres \
                    -e POSTGRES_DB=api_development \
                    -p 5432:5432 \
                    --rm postgres:9.6.9-alpine
    hugo:
        dir: static
        cmds:
            - hugo server
    elm:
        dir: static
        cmds:
            # - ./elm-build.sh
            - elm make elm/Screencasts.elm --output=static/js/screencasts.elm.js
        sources:
            - static/elm/Screencasts.elm
        generates:
            - static/static/js/screencasts.elm.js
    caddy:
        cmds: ['caddy']
    install-caddy:
        cmds: ['curl https://getcaddy.com | bash -s personal']
