# This is a task file, for use with go-task. See https://taskfile.dev/#/ for details
#
# GH site for this tool: https://github.com/go-task/task
version: '2'

tasks:
    default:
        deps: [api, hugo, elm, caddy]
    api:
        dir: api
        cmds:
            - buffalo dev
    hugo:
        dir: static
        cmds:
            - hugo server
    elm:
        dir: static
        cmds:
            # - ./elm-build.sh
            - elm make elm/Screencasts.elm --output=static/js/screencasts.elm.js
        sources:
            - static/elm/Screencasts.elm
        generates:
            - static/static/js/screencasts.elm.js
    caddy:
        cmds: ['caddy']
    install-caddy:
        cmds: ['curl https://getcaddy.com | bash -s personal']
