name: Go for Modules
on: [push]
jobs:

  build:
    name: Build Go Code
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org

    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build all code
      uses: magefile/mage-action@v1
      with:
        version: v1.5.0
        args: buildall
